language: elixir
matrix:
  include:
    - elixir: 1.4.5
      otp_release: 19.2
    - elixir: 1.5.3
      otp_release: 20.3.1
    - elixir: 1.6.6
      otp_release: 20.1
    - elixir: 1.7.0
      otp_release: 21.0.3
    - elixir: 1.8.1
      otp_release: 21.0.9
script:
  - "MIX_ENV=test mix do deps.get, compile, coveralls.travis"
